apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ctlog.fullname" . }}
{{ include "ctlog.namespace" . | indent 2 }}
  labels:
    {{- include "ctlog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      {{- include "ctlog.matchLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/ctlog-configmap.yaml") . | sha256sum }}
        {{- if .Values.server.podAnnotations }}
        {{- toYaml .Values.server.podAnnotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "ctlog.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "ctlog.serviceAccountName" . }}
      containers:
        - name: {{ template "ctlog.fullname" . }}
          image: "{{ template "ctlog.image" .Values.server.image }}"
          imagePullPolicy: "{{ .Values.server.image.pullPolicy }}"
          args:
{{  include "ctlog.server.args" . | indent 12 }}
          volumeMounts:
            - name: keys
              mountPath: "/ctfe-keys"
              readOnly: true
            - name: config
              mountPath: "/ctfe-config"
              readOnly: true
          ports:
{{- include "ctlog.containerPorts" .Values.server.service.ports | indent 12 }}
    {{- if .Values.server.resources }}
          resources:
{{ toYaml .Values.server.resources | indent 12 }}
    {{- end }}
    {{- if .Values.server.securityContext }}
      securityContext:
{{ toYaml .Values.server.securityContext | indent 8 }}
    {{- end }}
      volumes:
        - name: keys
          secret:
            secretName: {{ template "ctlog.secret" . }}
            items:
              - key: private
                path: privkey.pem
              - key: public
                path: pubkey.pem
              - key: rootca
                path: roots.pem
        - name: config
          {{- if .Values.server.config.secret.enabled }}
          secret:
            secretName: {{ .Values.server.config.secret.name }}
            items:
              - key: config
                path: ct_server.cfg
          {{ else }}
          configMap:
            name: {{ template "ctlog.config" . }}
            items:
              - key: config
                path: ct_server.cfg
          {{- end }}
