forceNamespace: ""
imagePullSecrets: []
serviceAccountName: tuf
roleName: tuf
roleBindingName: tuf
fullnameOverride: tuf
enabled: true

deployment:
  name: tuf
  replicas: 1
  registry: ghcr.io
  repository: sigstore/scaffolding/server
  # v0.6.9
  version: sha256:ce3a26f3cb86a370c12316f43660ec58f6954c359d4ae5daa209141d9e52df67
  imagePullPolicy: IfNotPresent
  port: 8080

secrets:
  rekor:
    create: false
    name: rekor-public-key
    key: key
    path: rekor-pubkey
  fulcio:
    create: false
    name: fulcio-server-secret
    key: cert
    path: fulcio-cert
  ctlog:
    create: false
    name: ctlog-public-key
    key: public
    path: ctlog-pubkey

ingress:
  create: true
  name: tuf-server
  className: nginx
  annotations: {}
  http:
    hosts:
    - path: /
      host: "tuf.localhost"

service:
  name: tuf-server
  port: 80

namespace:
  create: false
  name: fulcio-system
