apiVersion: v2
name: ctlog
description: Certificate Log

type: application

version: 0.2.50
appVersion: 0.6.14

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: ct_server
      image: ghcr.io/sigstore/scaffolding/ct_server:v0.6.14@sha256:7a2f69676bbfe4d93554c662117e7520f9250684e60c2861dc62af6a18b01e18
    - name: createctconfig
      image: ghcr.io/sigstore/scaffolding/createctconfig:v0.6.14@sha256:4e1446a12f32dd8e7bbc7a48c74579de329307feb5cd5e467b15d216ceb4ae45
    - name: createtree
      image: ghcr.io/sigstore/scaffolding/createtree:v0.6.14@sha256:fe4f41981fce2d6497b9f6a8e9dbdf3b0f3a5396feda6341090f363020ffb8bb
    - name: curlimages/curl
      image: docker.io/curlimages/curl:8.5.0@sha256:4bfa3e2c0164fb103fb9bfd4dc956facce32b6c5d47cc09fcec883ce9535d5ac
