apiVersion: v2
name: ctlog
description: Certificate Log

type: application

version: 0.2.48
appVersion: 0.6.10

keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: ct_server
      image: ghcr.io/sigstore/scaffolding/ct_server:v0.6.10@sha256:ef9ed3f5b9dd4f886c658505bff63c020063f96cd4634a5ddae2e66dad1c3264
    - name: createctconfig
      image: ghcr.io/sigstore/scaffolding/createctconfig:v0.6.10@sha256:bc093cafb95a87461ac3215d7ce3ef7d0a1fa2d0db17e119415061f781d7848d
    - name: createtree
      image: ghcr.io/sigstore/scaffolding/createtree:v0.6.10@sha256:1c8c06786a981344b5643443a4f62580e36a49e02f08783511a2766d5e0081ad
    - name: curlimages/curl
      image: docker.io/curlimages/curl:8.4.0@sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af
