namespace:
  create: false
  name: ctlog-system
server:
  replicaCount: 1
  config:
    secret:
      enabled: false
      name: ctlog-config
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/ct_server
    pullPolicy: IfNotPresent
    # v0.2.9
    version: "sha256:6f5ec5dbff8f886b3b56ff206b8e836fe564bbd64a1436ac8c5e7ae341163e24"
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: false
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "6963"
  portHTTP: 6962
  portHTTPMetrics: 6963
  service:
    type: ClusterIP
    ports:
      - name: 6962-tcp
        port: 80
        protocol: TCP
        targetPort: 6962
      - name: 6963-tcp
        port: 6963
        protocol: TCP
        targetPort: 6963
  ingress:
    enabled: false
    className: nginx
    hosts:
      - path: /
    annotations: {}
    tls: []
  extraArgs: []
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
createtree:
  enabled: true
  name: createtree
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createtree
    pullPolicy: IfNotPresent
    # v0.2.9
    version: "sha256:b8bbd91bafb1312719ae0d1a59c1deec3c90e74d5f91a16c419841f786b8fc96"
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
createctconfig:
  enabled: true
  replicaCount: 1
  name: createctconfig
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createctconfig
    pullPolicy: IfNotPresent
    # v0.2.9
    version: "sha256:7412243415a984b697a630b2f0b322a519285abc5c458053790e4e5f9a4156b2"
  fulcioURL: "http://fulcio-server.fulcio-system.svc"
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533
trillian:
  namespace: trillian-system
  logServer:
    name: trillian-logserver
    portRPC: 8091
# Force namespace of namespaced resources
forceNamespace: ""
