{{- if (not .Values.mysql.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.mysql.secret.annotations }}
  annotations:
{{ toYaml .Values.mysql.secret.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "rekor.mysql.labels" . | nindent 4 }}
{{- if .Values.mysql.secret.labels }}
{{ toYaml .Values.mysql.secret.labels | indent 4 }}
{{- end }}
  name: {{ template "rekor.mysql.fullname" . }}
{{ include "rekor.namespace" . | indent 2 }}
type: Opaque
data:
  {{- if .Values.mysql.enabled -}}
  {{- if not (empty .Values.mysql.auth.rootPassword) }}
  mysql-root-password: {{ .Values.auth.rootPassword | b64enc | quote }}
  {{- else }}
  mysql-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not (empty .Values.mysql.auth.password) }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  {{- else }}
  mysql-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}