enabled: false
namespace:
  name: trillian-system
  create: false
serviceAccount:
  name: trillian-logserver
  annotations: {}
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/updatetree:v0.6.14@sha256:0afd3cdcb447c8f0243a89e408fe5ece3f745a054b067f397331c4add9380153
ttlSecondsAfterFinished: 3600
securityContext:
  runAsNonRoot: true
  runAsUser: 65533
args:
  treeID: ""
   # -- valid tree states are ACTIVE, FROZEN and DRAINING
  treeState: ""
annotations: {}

# Configure Trillian dependency
trillian:
  namespace: trillian-system
  adminServer: ""
  logServer:
    name: trillian-logserver
    portRPC: 8091
