namespace:
  create: false
  name: tsa-system

server:
  replicaCount: 1
  name: server
  svcPort: 80
  grpcSvcPort: 5554
  secret: tsa-server-secret
  logging:
    production: false
  env:
    GOOGLE_APPLICATION_CREDENTIALS: /etc/tsa-config/cloud_credentials
  image:
    registry: ghcr.io
    repository: sigstore/timestamp-server
    pullPolicy: IfNotPresent
    # crane digest ghcr.io/sigstore/timestamp-server:v1.2.0
    # -- v1.2.0
    version: sha256:727e868e9ba9b181029d8e7d52f7153af53d9b0678c463e86c30985aae5cb2b5
  args:
    port: 5555
    # Valid values: tink, kms, file
    signer: tink
    # PEM encoded cert chain here. Order from active intermedate first to root last
    cert_chain: chain
    tink_enc_keyset: keyset
    tink_key_resource: resource
    tink_hcvault_token: token
    kms_key_resource: resource
  serviceAccount:
    create: true
    name: ""
    annotations: {}
    mountToken: true
  service:
    type: ClusterIP
    ports:
      - name: http
        port: 80
        protocol: TCP
        targetPort: 5555
      - name: metrics
        port: 2112
        protocol: TCP
        targetPort: 2112
  ingress:
    http:
      enabled: true
      className: "nginx"
      annotations: {}
      hosts:
      - path: /
        host: "timestamp.localhost"
      tls: []
  securityContext:
    runAsNonRoot: true
    runAsUser: 65533

# Force namespace of namespaced resources
forceNamespace: ""
