apiVersion: v2
description: The Helm chart for Policy  Controller
home: https://github.com/sigstore/policy-controller

sources:
  - https://github.com/sigstore/policy-controller

type: application

name: policy-controller
version: 0.1.30
appVersion: 0.2.0

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: policy-controller
      image: gcr.io/projectsigstore/policy-controller:v0.2.0@sha256:63cd54b877bcd8b3d6d6b7110955e3f773bd8ad5b16d1b6133d4009c26c6da18
    - name: policywebhook
      image: gcr.io/projectsigstore/policy-webhook:v0.2.0@sha256:de980929f4ac04f4e91ca2cfeeb341ba9a8a848407158711570435ae9253b4b4
