cosign:
  # add the values in base64 encoded
  cosignPub: ""
  webhookName: "policy.sigstore.dev"

imagePullSecrets: []

policywebhook:
  replicaCount: 1
  image:
    repository: ghcr.io/sigstore/policy-controller/policy-webhook
    # crane digest ghcr.io/sigstore/policy-controller/policy-webhook:v0.4.1
    version: sha256:47c96a74c31c48c5a082100ec94d766bb668ec015b74558bc37619781351c798
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceAccount:
    annotations: {}
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
  service:
    annotations: {}
    type: ClusterIP
    port: 443
  webhookNames:
    defaulting: "defaulting.clusterimagepolicy.sigstore.dev"
    validating: "validating.clusterimagepolicy.sigstore.dev"

webhook:
  replicaCount: 1
  name: webhook
  image:
    repository: ghcr.io/sigstore/policy-controller/policy-controller
    # crane digest ghcr.io/sigstore/policy-controller/policy-controller:v0.4.1
    version: sha256:4c38700ec69f82b405fdd6cbc38a0eeb7ca3482dfe2d21f1be2929f845fb7bd7
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    capabilities:
      drop:
        - ALL
  serviceAccount:
    annotations: {}
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>
  volumeMounts: []
  volumes: []

## common node selector for all the pods
commonNodeSelector: {}
#  key1: value1
#  key2: value2

## common tolerations for all the pods
commonTolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

## serviceMonitor makes policy controller metrics discoverable to prometheus
serviceMonitor:
  enabled: false
