cosign:
  secretKeyRef:
    name: ""
  # add the values in base64 encoded
  cosignPub: ""
  webhookName: "policy.sigstore.dev"

imagePullSecrets: []

policywebhook:
  replicaCount: 1
  image:
    repository: ghcr.io/sigstore/policy-controller/policy-webhook
    # crane digest ghcr.io/sigstore/policy-controller/policy-webhook:v0.3.0
    version: sha256:d1e7af59381793687db4673277005276eb73a06cf555503138dd18eaa1ca47d6
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceAccount:
    annotations: {}
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
        - all
  service:
    annotations: {}
    type: ClusterIP
    port: 443
  webhookNames:
    defaulting: "defaulting.clusterimagepolicy.sigstore.dev"
    validating: "validating.clusterimagepolicy.sigstore.dev"

webhook:
  replicaCount: 1
  name: webhook
  image:
    repository: ghcr.io/sigstore/policy-controller/policy-controller
    # crane digest ghcr.io/sigstore/policy-controller/policy-controller:v0.3.0
    version: sha256:dba911635cd4f12ac807d3cd2e9065f6ec131102fa7cf19e75e897d0efe2247f
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    capabilities:
      drop:
        - all
  serviceAccount:
    annotations: {}
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>

## common node selector for all the pods
commonNodeSelector: {}
#  key1: value1
#  key2: value2

## common tolerations for all the pods
commonTolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

## serviceMonitor makes policy controller metrics discoverable to prometheus
serviceMonitor:
  enabled: false
