namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober@sha256:ef5542e75d5f396e2cec02a8901d69abf33a263b2a98c1cf8391da341fe89efa  # v0.6.1
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  args:
    fulcioHost: https://fulcio.sigstore.dev
    rekorHost: https://rekor.sigstore.dev
    frequency: 10
    writeProber: false
    rekorRequests: []
    fulcioRequests: []
    trustRekorAPIPublicKey: false
prometheus:
  port: 8080
