namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober:v0.6.8@sha256:beda55da0ae20d0d94b5cb31815a30a9d446cf452206c7fd8bddeec102604520
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "200m"
  args:
    fulcioHost: https://fulcio.sigstore.dev
    rekorHost: https://rekor.sigstore.dev
    frequency: 10
    writeProber: false
    rekorRequests: []
    fulcioRequests: []
    trustRekorAPIPublicKey: false
prometheus:
  port: 8080
