namespace:
  create: true
  name: sigstore-prober
serviceAccount:
  name: default
  create: false
spec:
  replicaCount: 1
  image: ghcr.io/sigstore/scaffolding/prober@sha256:59093231a8048aafcdd43a2b6b3bca29069f97a5737850f336118abb560f857e  # v0.4.3
  imagePullPolicy: Always
  matchLabels:
    app: sigstore-prober
  args:
    fulcioHost: https://fulcio.sigstore.dev
    rekorHost: https://rekor.sigstore.dev
    frequency: 10
prometheus:
  port: 8080
