{{- if .Values.cosign.cosignPub }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "cosigned.labels" . | nindent 4 }}
  name: {{ template "cosigned.fullname" . }}-cosign-key
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  cosign.key: {{ default "" .Values.cosign.cosignKey}}
  cosign.password: {{ default "" .Values.cosign.cosignPassword}}
  cosign.pub: {{ .Values.cosign.cosignPub}}
{{- end -}}