apiVersion: v1
kind: Secret
metadata:
  annotations:
    {{- if .Values.webhook.service.annotations }}
    {{ toYaml .Values.webhook.service.annotations | nindent 4 }}
    {{- end }}
  labels:
    {{- include "cosigned.labels" . | nindent 4 }}
    control-plane: {{ template "cosigned.fullname" . }}-webhook
  name: webhook-certs
  namespace: {{ .Release.Namespace }}
# The data is populated at install time.
