{{ if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.rekor.name }}
{{ include "tuf.namespace" . | indent 2 }}
type: Opaque
data:
  {{ .Values.secrets.rekor.key }}: {{ .Values.secrets.rekor.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.fulcio.name }}
{{ include "tuf.namespace" . | indent 2 }}
type: Opaque
data:
  {{ .Values.secrets.fulcio.key }}: {{ .Values.secrets.fulcio.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.ctlog.name }}
{{ include "tuf.namespace" . | indent 2 }}
type: Opaque
data:
  {{ .Values.secrets.ctlog.key }}: {{ .Values.secrets.ctlog.value }}
{{ end }}