apiVersion: v2
name: rekor
description: Part of the sigstore project, Rekor is a timestamping server and transparency log for storing signatures, as well as an API based server for validation

type: application

version: 1.3.13
appVersion: 1.3.3

keywords:
  - security
  - transparency logs

home: https://sigstore.dev/
sources:
  - https://github.com/sigstore/rekor
maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: trillian
    version: 0.2.17
    repository: https://sigstore.github.io/helm-charts
    condition: trillian.enabled

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: createtree
      image: ghcr.io/sigstore/scaffolding/createtree:v0.6.9@sha256:acd6f2bc2ad9bac400f86fc08d7c1042e0727fe6d0360a36b958ca25208d627a
    - name: curlimages/curl
      image: docker.io/curlimages/curl:8.4.0@sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af
    - name: rekor-server
      image: gcr.io/projectsigstore/rekor-server:v1.3.3@sha256:48c206d669a71783dd0013a75420813cbd63a300975d3b4c32237d6cf76d1182
    - name: redis
      image: docker.io/redis:6.2.14-alpine3.18@sha256:452b7655bda0e270a6376b71d22fcb30662e745dcb4728f99fa87f01287b465d
    - name: backfill-redis
      image: ghcr.io/sigstore/rekor/backfill-redis:v1.3.3@sha256:7616a8808140274ccde39e6a41e2bf5e5f5c83b9e57d83feddf0308428ea40c9
