{{- if .Values.server.ingress.http.enabled }}
apiVersion: {{ include "ingress.apiVersion" .}}
kind: Ingress
metadata:
  labels:
    {{- include "fulcio.labels" . | nindent 4 }}
  name: {{ template "fulcio.fullname" . }}-http
{{ include "fulcio.namespace" . | indent 2 }}
  annotations:
{{ toYaml .Values.server.ingress.http.annotations | indent 4 }}
spec:
  rules:
    {{- range .Values.server.ingress.http.hosts }}
    - host: {{ required "An Ingress hostname is required" .host | quote }}
      http:
        paths:
          - path: {{ .path }}
            {{- if eq "true" (include "ingress.supportsPathType" $) }}
            pathType: {{ default "Prefix" .pathType }}
            {{- end }}
            backend: {{- include "fulcio.server.ingress.backend" (list $ . $.Values.server.svcPort) | nindent 14 }}
    {{- end }}
{{- if .Values.server.ingress.tls }}
  tls:
    {{- range .Values.server.ingress.tls }}
    - hosts:
      {{- range .hosts }}
      - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
{{- end -}}
{{- end }}
