apiVersion: v2
name: scaffold
description: Scaffolding the components of the sigstore architecture

type: application

version: 0.6.34
keywords:
  - security
  - pki

home: https://sigstore.dev/

maintainers:
  - name: The Sigstore Authors

dependencies:
  - name: fulcio
    version: 2.3.13
    repository: https://sigstore.github.io/helm-charts
    condition: fulcio.enabled
  - name: rekor
    version: 1.3.12
    repository: https://sigstore.github.io/helm-charts
    condition: rekor.enabled
  - name: trillian
    version: 0.2.16
    repository: https://sigstore.github.io/helm-charts
    condition: trillian.enabled
  - name: ctlog
    version: 0.2.47
    repository: https://sigstore.github.io/helm-charts
    condition: ctlog.enabled
  - name: tuf
    version: 0.1.7
    repository: https://sigstore.github.io/helm-charts
    condition: tuf.enabled
  - name: tsa
    version: 1.0.1
    repository: https://sigstore.github.io/helm-charts
    condition: tsa.enabled

annotations:
  artifacthub.io/license: Apache-2.0
