apiVersion: v2
name: trillian
description: |
  Trillian is a log that stores an accurate, immutable and verifiable history of activity.

type: application

version: 0.2.16

keywords:
  - security
  - pki

home: https://sigstore.dev/
sources:
  - https://github.com/google/trillian
  - https://github.com/sigstore/helm-charts/tree/main/charts/trillian

maintainers:
  - name: The Sigstore Authors
    url: https://sigstore.dev/

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: curl
      image: docker.io/curlimages/curl:8.4.0@sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af
    - name: netcat
      image: cgr.dev/chainguard/netcat@sha256:7243b469d34bd28969fa2c764a12d91084c427209540bb68645629d635b3f143
    - name: db_server
      image: gcr.io/trillian-opensource-ci/db_server@sha256:c04753ed44eac715e3191dad16fb0848a06714ddcb00c6f7768bf065485e1f8d
    - name: log_server
      image: gcr.io/projectsigstore/trillian_log_server@sha256:ab60d5e16675fc15783ec8dbc99a335b68b9a0dd6dd4495ecc300c5f8aa58b72
    - name: log_signer
      image: gcr.io/projectsigstore/trillian_log_signer@sha256:54a75e22beb4cb90b7aef63a28ac9e33fee60b35a66a2b9e7d6444a40e2b6a79
    - name: cloud_proxy
      image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.7.1-alpine@sha256:38b31e81da387542027b9d4b67c6c83704e12e6766c5c5ad3013aaf51e4cf540
    - name: scaffold_cloud_proxy
      image: ghcr.io/sigstore/scaffolding/cloudsqlproxy:v0.6.9@sha256:3c6bf9b6bfc299d8a96de7771b5226a5f7bcce1b7893c039393f1dec5e66c799
    - name: createdb
      image: ghcr.io/sigstore/scaffolding/createdb:v0.6.9@sha256:b4a79c60c0dc9019e25d9b2d41d62c5fbd16be56d73df980b0ab3491a2bcb8c8
