namespace:
  create: false
  name: trillian-system

imagePullSecrets: []

initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    # -- 8.4.0
    version: sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af
    imagePullPolicy: IfNotPresent
  netcat:
    registry: cgr.dev
    repository: chainguard/netcat
    # -- 2023-06-13
    version: "sha256:7243b469d34bd28969fa2c764a12d91084c427209540bb68645629d635b3f143"
    imagePullPolicy: IfNotPresent

storageSystem:
  driver: mysql
  envCredentials: null
quotaSystem:
  driver: mysql

mysql:
  gcp:
    enabled: false
    instance: ""
    scaffoldSQLProxy:
      registry: ghcr.io
      repository: sigstore/scaffolding/cloudsqlproxy
      # -- v0.6.10 which is based on cloud-sql-proxy:2.7.2-alpine
      version: sha256:7aca1e897b40958fa30bdf41161095c48ae1fc2a8b31f0e9c7742acbf182a125
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
    cloudsql:
      registry: gcr.io
      repository: cloud-sql-connectors/cloud-sql-proxy:2.7.2-alpine
      # -- crane digest cloud-sql-connectors/cloud-sql-proxy:2.7.2-alpine
      version: sha256:2514634b2b398db63ba7bf2222dc243a84f281285d3b5a406fc1a19f9c0b816b
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      unixDomainSocket:
        enabled: false
        path: /cloudsql
  enabled: true
  replicaCount: 1
  name: mysql
  hostname: ""
  port: 3306
  strategy:
    type: Recreate
  image:
    registry: gcr.io
    repository: trillian-opensource-ci/db_server
    pullPolicy: IfNotPresent
    # -- crane digest gcr.io/trillian-opensource-ci/db_server:v1.5.3
    version: sha256:2a685a38dd0129cceb646c232d285383f614c7e6fa51ff8f512aef78e4298461
  resources: {}
  args:
    - "--ignore-db-dir=lost+found"
  service:
    type: ClusterIP
    ports:
      - name: 3306-tcp
        port: 3306
        protocol: TCP
        targetPort: 3306
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  secret:
    annotations: {}
  auth:
    username: "mysql"
    password: ""
    rootPassword: ""
    existingSecret: ""
  persistence:
    enabled: true
    annotations: {}
    storageClass: null
    size: 5Gi
    mountPath: /var/lib/mysql
    subPath: ""
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
  serviceAccount:
    create: true
    name: ""
    annotations: {}

logServer:
  enabled: true
  replicaCount: 1
  name: log-server
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: gcr.io
    repository: projectsigstore/trillian_log_server
    pullPolicy: IfNotPresent
    # -- v1.5.3 from rekor v1.3.3 build
    version: sha256:0570f8561677e6140a73cb2d7e04e19cf52eb955efe40297e23402694d19489b

  nodeSelector: {}

  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
      - name: 8090-tcp
        port: 8090
        protocol: TCP
        targetPort: 8090
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}

logSigner:
  enabled: true
  replicaCount: 1
  name: log-signer
  forceMaster: true
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: gcr.io
    repository: projectsigstore/trillian_log_signer
    pullPolicy: IfNotPresent
    # -- v1.5.3 from rekor v1.3.3 build
    version: sha256:948291659bb9910708900aad33dd18669d001ea5e93b85404634bab8e38c83d7

  nodeSelector: {}

  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}

createdb:
  enabled: true
  dbname: trillian
  ttlSecondsAfterFinished: 3600
  name: createdb
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createdb
    pullPolicy: IfNotPresent
    # -- v0.6.10
    version: sha256:f9442ce8323163ffe876e9b10da196b361074d8865a0ef963f3879c61863595b
  serviceAccount:
    create: false
    name: ""
    annotations: {}
# Force namespace of namespaced resources
forceNamespace: ""
