namespace:
  create: false
  name: trillian-system

imagePullSecrets: []

initContainerImage:
  curl:
    registry: docker.io
    repository: curlimages/curl
    # -- 8.4.0
    version: sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af
    imagePullPolicy: IfNotPresent
  netcat:
    registry: cgr.dev
    repository: chainguard/netcat
    # -- 2023-06-13
    version: "sha256:7243b469d34bd28969fa2c764a12d91084c427209540bb68645629d635b3f143"
    imagePullPolicy: IfNotPresent

storageSystem:
  driver: mysql
  envCredentials: null
quotaSystem:
  driver: mysql

mysql:
  gcp:
    enabled: false
    instance: ""
    scaffoldSQLProxy:
      registry: ghcr.io
      repository: sigstore/scaffolding/cloudsqlproxy
      # -- v0.6.9 which is based on cloud-sql-proxy:2.7.1-alpine
      version: sha256:3c6bf9b6bfc299d8a96de7771b5226a5f7bcce1b7893c039393f1dec5e66c799
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
    cloudsql:
      registry: gcr.io
      repository: cloud-sql-connectors/cloud-sql-proxy:2.7.1-alpine
      # -- crane digest cloud-sql-connectors/cloud-sql-proxy:2.7.1-alpine
      version: sha256:38b31e81da387542027b9d4b67c6c83704e12e6766c5c5ad3013aaf51e4cf540
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      unixDomainSocket:
        enabled: false
        path: /cloudsql
  enabled: true
  replicaCount: 1
  name: mysql
  hostname: ""
  port: 3306
  strategy:
    type: Recreate
  image:
    registry: gcr.io
    repository: trillian-opensource-ci/db_server
    pullPolicy: IfNotPresent
    # -- crane digest gcr.io/trillian-opensource-ci/db_server:v1.5.2
    version: sha256:c04753ed44eac715e3191dad16fb0848a06714ddcb00c6f7768bf065485e1f8d
  resources: {}
  args:
    - "--ignore-db-dir=lost+found"
  service:
    type: ClusterIP
    ports:
      - name: 3306-tcp
        port: 3306
        protocol: TCP
        targetPort: 3306
  livenessProbe:
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 1
    failureThreshold: 3
    successThreshold: 1
    exec:
      command:
        - /etc/init.d/mysql
        - status
  secret:
    annotations: {}
  auth:
    username: "mysql"
    password: ""
    rootPassword: ""
    existingSecret: ""
  persistence:
    enabled: true
    annotations: {}
    storageClass: null
    size: 5Gi
    mountPath: /var/lib/mysql
    subPath: ""
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
  serviceAccount:
    create: true
    name: ""
    annotations: {}

logServer:
  enabled: true
  replicaCount: 1
  name: log-server
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: gcr.io
    repository: projectsigstore/trillian_log_server
    pullPolicy: IfNotPresent
    # -- v1.3.0 from rekor build
    version: sha256:ab60d5e16675fc15783ec8dbc99a335b68b9a0dd6dd4495ecc300c5f8aa58b72

  nodeSelector: {}

  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
      - name: 8090-tcp
        port: 8090
        protocol: TCP
        targetPort: 8090
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}

logSigner:
  enabled: true
  replicaCount: 1
  name: log-signer
  forceMaster: true
  portRPC: 8091
  portHTTP: 8090
  image:
    registry: gcr.io
    repository: projectsigstore/trillian_log_signer
    pullPolicy: IfNotPresent
    # -- v1.3.0 from rekor build
    version: sha256:54a75e22beb4cb90b7aef63a28ac9e33fee60b35a66a2b9e7d6444a40e2b6a79

  nodeSelector: {}

  service:
    type: ClusterIP
    ports:
      - name: 8091-tcp
        port: 8091
        protocol: TCP
        targetPort: 8091
  livenessProbe: {}
  readinessProbe: {}
  resources: {}
  extraArgs: []
  serviceAccount:
    create: true
    name: ""
    annotations: {}

createdb:
  enabled: true
  dbname: trillian
  ttlSecondsAfterFinished: 3600
  name: createdb
  image:
    registry: ghcr.io
    repository: sigstore/scaffolding/createdb
    pullPolicy: IfNotPresent
    # -- v0.6.9
    version: sha256:b4a79c60c0dc9019e25d9b2d41d62c5fbd16be56d73df980b0ab3491a2bcb8c8
  serviceAccount:
    create: false
    name: ""
    annotations: {}
# Force namespace of namespaced resources
forceNamespace: ""
