apiVersion: v2
description: The Helm chart for Cosigned
home: https://github.com/sigstore/cosign

sources:
  - https://github.com/sigstore/cosign

type: application

name: cosigned
version: v0.1.7
appVersion: v1.4.0

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: cosigned
      image: gcr.io/projectsigstore/cosigned:v1.4.0@sha256:e8cab7aaa67116da504d5eeab88d2094faf7592530c244e8bc3760a93f989b31
