apiVersion: v2
description: The Helm chart for Cosigned
home: https://github.com/sigstore/cosign
sources:
  - https://github.com/sigstore/cosign
name: cosigned
type: application
version: v0.0.3-dev
appVersion: "dev"
maintainers:
  - name: dlorenc
  - name: hectorj2f
