apiVersion: v2
description: The Helm chart for Cosigned
home: https://github.com/sigstore/cosign

sources:
  - https://github.com/sigstore/cosign

type: application

name: cosigned
version: v0.1.1
appVersion: v1.3.0

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: cosigned
      image: gcr.io/projectsigstore/cosigned:1.3.0@sha256:9fe107b183d6c6badaca52e380720c0549db09b645d055f00601797f48060aa2
