apiVersion: v2
description: The Helm chart for Cosigned
home: https://github.com/sigstore/cosign

sources:
  - https://github.com/sigstore/cosign

type: application

name: cosigned
version: 0.1.19
appVersion: 1.8.0

maintainers:
  - name: dlorenc
  - name: hectorj2f

annotations:
  artifacthub.io/license: Apache-2.0
  artifacthub.io/images: |
    - name: cosigned
      image: gcr.io/projectsigstore/cosigned:v1.8.0@sha256:784518ff3ee755ce42e174e61036094af771c43bdc76b65a8f0e52481ed450ac
    - name: policywebhook
      image: gcr.io/projectsigstore/policy-webhook:v1.8.0@sha256:82940e8c3e0d3d5dd92b4779f4378e664f91b790db0d799b03535648eddc141d
