cosign:
  # add the values in base64 encoded
  cosignKey:
  cosignPub:
  cosignPassword:

webhook:
  name: webhook
  image:
    repository: gcr.io/projectsigstore/cosign/ci/cosigned
    version: sha256:33fe35284cb3648cdd998f6ed6524e1d7b69a3edbf1234bf39a1547ecf27b28f
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
      - all
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>

## common node selector for all the pods
commonNodeSelector: {}
#  key1: value1
#  key2: value2

## common tolerations for all the pods
commonTolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"
