cosign:
  secretKeyRef:
    name:
  # add the values in base64 encoded
  cosignKey:
  cosignPub:
  cosignPassword:


webhook:
  name: webhook
  image:
    repository: gcr.io/projectsigstore/cosigned
    # crane digest gcr.io/projectsigstore/cosigned:1.3.0
    version: sha256:9fe107b183d6c6badaca52e380720c0549db09b645d055f00601797f48060aa2
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    capabilities:
      drop:
      - all
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>

## common node selector for all the pods
commonNodeSelector: {}
#  key1: value1
#  key2: value2

## common tolerations for all the pods
commonTolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

## serviceMonitor makes cosigned metrics discoverable to prometheus
serviceMonitor:
  enabled: false
