cosign:
  secretKeyRef:
    name: ""
  # add the values in base64 encoded
  cosignPub: ""
  webhookName: "cosigned.sigstore.dev"

policywebhook:
  image:
    repository: gcr.io/projectsigstore/policy-webhook
    version: sha256:59fd679d6629fbfa99b4413771dca16cb7891b0a91dd386dc46ea9fac46bcfbc
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceAccount:
    annotations: {}
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    capabilities:
      drop:
      - all
  service:
    annotations: {}
    type: ClusterIP
    port: 443

webhook:
  name: webhook
  image:
    repository: gcr.io/projectsigstore/cosigned
    # crane digest gcr.io/projectsigstore/cosigned:v1.7.2
    version: sha256:766698b7c472ee4c37133a92203def72c90c3c49e2b334130e6e3a100254911e
    pullPolicy: IfNotPresent
  env: {}
  extraArgs: {}
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  securityContext:
    enabled: false
    runAsUser: 65532
  podSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsUser: 1000
    capabilities:
      drop:
        - all
  serviceAccount:
    annotations: {}
  service:
    annotations: {}
    type: ClusterIP
    port: 443
    # For nodeport, specify the following:
    #   type: NodePort
    #   nodePort: <port-number>

## common node selector for all the pods
commonNodeSelector: {}
#  key1: value1
#  key2: value2

## common tolerations for all the pods
commonTolerations: []
# - key: "key"
#   operator: "Equal"
#   value: "value"
#   effect: "NoSchedule"

## serviceMonitor makes cosigned metrics discoverable to prometheus
serviceMonitor:
  enabled: false
