apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sigstore-prober.name" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      {{- include "sigstore-prober.common.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sigstore-prober.common.matchLabels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "{{ .Values.prometheus.port }}"
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- if .Values.spec.args.trustRekorAPIPublicKey }}
      initContainers:
      - name: public-key-fetcher
        image: docker.io/curlimages/curl@sha256:4a3396ae573c44932d06ba33f8696db4429c419da87cbdc82965ee96a37dd0af
        args:
          - "--output"
          - "/var/run/sigstore/public-key.pem"
          - "{{ .Values.spec.args.rekorHost }}/api/v1/log/publicKey"
        env:
        volumeMounts:
        - name: sigstore
          mountPath: "/var/run/sigstore"
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
      {{- end }}
      containers:
      - name: {{ template "sigstore-prober.name" . }}
        image: "{{ .Values.spec.image }}"
        resources:
        {{- with .Values.spec.resources }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        imagePullPolicy: "{{ .Values.spec.imagePullPolicy }}"
        args:
          {{- include "sigstore-prober.args" . | nindent 8 }}
        ports:
        - containerPort: {{ .Values.prometheus.port }} # metrics
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
          allowPrivilegeEscalation: false
      {{- if .Values.spec.args.trustRekorAPIPublicKey }}
        env:
        - name: SIGSTORE_REKOR_PUBLIC_KEY
          value: "/var/run/sigstore/public-key.pem"
        volumeMounts:
        - name: sigstore
          mountPath: "/var/run/sigstore"
          readOnly: true
      volumes:
        - name: sigstore
          emptyDir: {}
      {{- end }}
